[book]
title = "Jammin Documentation"
authors = ["Fluffy Labs"]
description = "Guides and references for building with Jammin."
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
git-repository-url = "https://github.com/fluffylabs/jammin"
