name: Build - Docker - Jade

on:
  push:
    branches: ["main"]
    paths:
      - "docker/jade/VERSION"
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: image-version
        run: |
          VERSION=$(cat docker/jade/VERSION | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: docker/jade/jade.Dockerfile
          tags: jade:${{ steps.image-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout code examples
        uses: actions/checkout@v4
        with:
          repository: tomusdrw/jam-examples
          path: jam-examples

      - name: Test Docker image
        run: |
          docker run --rm -v ./jam-examples/empty-jade:/app jade:${{ steps.image-version.outputs.version }}

      - name: Save Docker image
        run: |
          docker save jade:${{ steps.image-version.outputs.version }} | gzip > jade-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: jade-docker-image
          path: jade-image.tar.gz
          retention-days: 1

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/jade/jade.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/fluffylabs/jammin-jade:${{ steps.image-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
