name: Build - Docker - JAM SDK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract package version
        id: package-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Dockerfile changed
        id: dockerfile-changed
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "docker/jam-sdk/jam-sdk.Dockerfile"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: docker/jam-sdk/jam-sdk.Dockerfile
          tags: jam-sdk
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout code examples
        uses: actions/checkout@v4
        with:
          repository: jammin-create/jammin-create-jam-sdk
          path: jam-sdk-example/services/example

      - name: Test Docker image
        run: |
          docker run --rm -v ./jam-sdk-example:/app jam-sdk jam-pvm-build -m service

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && steps.dockerfile-changed.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && steps.dockerfile-changed.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/jam-sdk/jam-sdk.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/fluffylabs/jammin-jam-sdk:${{ steps.package-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
