name: Build - Docker - Jade

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          file: docker/jade/jade.Dockerfile
          tags: jade
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout code examples
        uses: actions/checkout@v4
        with:
          repository: tomusdrw/jam-examples
          path: jam-examples

      - name: Test Docker image
        run: |
          docker run --rm -v ./jam-examples/empty-jade:/app jade

      - name: Save Docker image
        run: |
          docker save jade | gzip > jade-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: jade-docker-image
          path: jade-image.tar.gz
          retention-days: 1
